name: docs
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install .[docs]
      - name: Deploy github page
        working-directory: docs
        run: mkdocs gh-deploy --force --clean --verbose